name: Registry clean

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  registry_clean:
    name: Registry clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Run garbage collection
        run: doctl registry garbage-collection start -f --include-untagged-manifests
